package OlaApp;


/**
* OlaApp/Ola.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* quinta-feira, 17 de outubro de 2019 10:18:17 Horário da Guiana Francesa
*/

public interface Ola extends OlaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ola
