package OlaApp;


/**
* OlaApp/OlaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* quinta-feira, 17 de outubro de 2019 10:18:17 Horário da Guiana Francesa
*/

abstract public class OlaHelper
{
  private static String  _id = "IDL:OlaApp/Ola:1.0";

  public static void insert (org.omg.CORBA.Any a, OlaApp.Ola that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static OlaApp.Ola extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (OlaApp.OlaHelper.id (), "Ola");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static OlaApp.Ola read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OlaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, OlaApp.Ola value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static OlaApp.Ola narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OlaApp.Ola)
      return (OlaApp.Ola)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OlaApp._OlaStub stub = new OlaApp._OlaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static OlaApp.Ola unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof OlaApp.Ola)
      return (OlaApp.Ola)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      OlaApp._OlaStub stub = new OlaApp._OlaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
