package OlaApp;


/**
* OlaApp/OlaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Test.idl
* quinta-feira, 17 de outubro de 2019 10:18:17 Horário da Guiana Francesa
*/

public interface OlaOperations 
{
  String msg ();
  void msg (String newMsg);
} // interface OlaOperations
